name: issue transition
 
on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:
 
jobs:
  jira-transition:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo hello world
      run: echo "hello world"

    - name: Transition issue in Jira
      if: ${{ always() }}
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_HOST: https://bhavyass.atlassian.net
        JIRA_USERNAME: bhavyashrees@devtools.in
      run: |
        ISSUE_KEY="TS-11"
        TRANSITION_ID="31"
        curl -s -X POST \
          -H "Authorization: Basic $(echo -n $JIRA_USERNAME:$JIRA_API_TOKEN | base64)" \
          -H "Content-Type: application/json" \
          -d '{ "transition": { "id": "'"$TRANSITION_ID"'" } }' \
          "https://$JIRA_HOST/rest/api/2/issue/$ISSUE_KEY/transitions"
