name: issue transition
 
on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run a one-line script
        run: echo Hello, world!
 
      - name: Transition Jira Issue to Done
        if: github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000' && success()
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_KEY: "TS-11"
          JIRA_TRANSITION_ID: "21"
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{ "transition": { "id": "'"$JIRA_TRANSITION_ID"'" } }' \
            "https://bhavyass.atlassian.net/rest/api/2/issue/$JIRA_ISSUE_KEY/transitions"
