name: Transition Jira Issue

on: [push]

jobs:
  job1:
    runs-on: github24
    #environment: Dev
    
    steps:
      - name: Echo hello world
        run: echo "hello world"
      
  job2:
    runs-on: github24
    needs: job1
    if: success('job1')
    steps:
      - name: Transition Jira issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -X POST $JIRA_URL/rest/api/2/issue/TS-11/transitions \
            -H 'Accept: application/json' \
            -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
              "transition": {
                "id": "31"
              }
            }'
